export const presets = [
  {
    name: "1977",
    filters: {
      contrast: 110,
      brightness: 110,
      saturate: 130,
      "hue-rotate": 0,
      invert: 0,
      blur: 0,
      grayscale: 0,
      sepia: 0,
    },
    overlay: {
      type: "solid",
      blend: "screen",
      color1: { a: 0.3, b: 188, g: 106, r: 243 },
      opacity: 100,
    },
  },
  {
    name: "aden",
    filters: {
      "hue-rotate": 20,
      contrast: 90,
      saturate: 85,
      brightness: 120,
      invert: 0,
      blur: 0,
      grayscale: 0,
      sepia: 0,
    },
    overlay: {
      type: "linear",
      blend: "darken",
      direction: "to right",
      color1: { a: 0.2, b: 14, g: 10, r: 66 },
      color1Stop: 1,
      color2: { a: 0, b: 14, g: 10, r: 66 },
      color2Stop: 100,
      opacity: 100,
    },
  },
  {
    name: "amaro",
    filters: {
      contrast: 90,
      saturate: 150,
      brightness: 110,
      "hue-rotate": -10,
      invert: 0,
      blur: 0,
      grayscale: 0,
      sepia: 0,
    },
  },
  {
    name: "brannan",
    filters: {
      sepia: 50,
      contrast: 140,
      saturate: 100,
      brightness: 100,
      "hue-rotate": 0,
      invert: 0,
      blur: 0,
      grayscale: 0,
    },
    overlay: {
      type: "solid",
      blend: "lighten",
      color1: { a: 0.31, b: 199, g: 44, r: 161 },
      opacity: 100,
    },
  },
  {
    name: "clarendon",
    filters: {
      contrast: 120,
      saturate: 125,
      brightness: 100,
      "hue-rotate": 0,
      invert: 0,
      blur: 0,
      grayscale: 0,
      sepia: 0,
    },
    overlay: {
      type: "solid",
      blend: "overlay",
      color1: { a: 0.2, b: 227, g: 187, r: 127 },
      opacity: 100,
    },
  },
  {
    name: "gingham",
    filters: {
      contrast: 100,
      saturate: 100,
      brightness: 105,
      "hue-rotate": 350,
      invert: 0,
      blur: 0,
      grayscale: 0,
      sepia: 0,
    },
    overlay: {
      type: "linear",
      blend: "darken",
      direction: "to right",
      color1: { a: 0.2, b: 14, g: 10, r: 66 },
      color1Stop: 1,
      color2: { a: 0, b: 0, g: 0, r: 0 },
      color2Stop: 100,
      opacity: 100,
    },
  },
  {
    name: "inkwell",
    filters: {
      contrast: 110,
      saturate: 100,
      brightness: 110,
      "hue-rotate": 0,
      invert: 0,
      blur: 0,
      grayscale: 100,
      sepia: 30,
    },
    overlay: {
      type: "solid",
      blend: "darken",
      color1: { a: 0, b: 0, g: 0, r: 0 },
      opacity: 100,
    },
  },
];
